### ISSUE TITLE
Archive Manager

### ISSUE THREAD

**Issue by tenplus1** [BodhiDev/bodhi7packages#2]
Apologies if this is posted in the wrong package or section, but while using Bodhi's xarchiver I've had so many issues creating and unpacking archives that ended up with me removing it and installing Engrampa instead which works and feels a lot more native to the desktop.  Would you consider changing the default to Engrampa ?

**Comment by rbtylee** [comment]
Xarchive is not Bodhi's package it is in Ubuntu's repo. Apparently, Thunar Archive Plugin can use Engrampa as well as File-Roller. By default this plugin installed Xarchieve. I agree Xarchive is not the best. What would be the advantage of  Engrampa over File-Roller? I also agree that if I can get Thunar working with a better archive program that would be worth doing.

**Comment by tenplus1** [comment]
Engrampa is a fork of file roller and thankfully pulls in less dependencies so is a smaller install while still being drag & drop compatible with thunar.  Xubuntu uses Engrampa also if that helps.

**Comment by rbtylee** [comment]
Engrampa is currently being used on BL7.
