### ISSUE TITLE
Errors in postremoval scripts for bodhi-settings and nvidia-ppa

### ISSUE THREAD

**Issue by ZombieToof** [BodhiDev/bodhi7packages#4]
https://github.com/BodhiDev/bodhi7packages/blob/54db3fc29bb48fc82fcb9fdfe092006f1b01aede/bodhi/bodhi-settings/moksha/DEBIAN/prerm#L6-L8

The path in line 7 is missing a `/` and shoud be `rm /etc/apt/trusted.gpg.d/mozillateam-ubuntu-ppa.gpg`

https://github.com/BodhiDev/bodhi7packages/blob/54db3fc29bb48fc82fcb9fdfe092006f1b01aede/bodhi/nvidia-ppa/DEBIAN/prerm#L6-L8

The paths do not match. Line 7 should be `rm /etc/apt/trusted.gpg.d/kelebek333-ubuntu-nvidia-legacy.gpg`

**Comment by rbtylee** [comment]
Good catch. Thanks. Fixed here and I will repackage these sometime today :)
